name: Deploy BGS App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build BGS App
        run: npm install && npm run build

      - name: Install surge on match
        run: npm install -g surge

      - name: Run deployment on match
        run: surge ./public/ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
