name: Deploy Unoscore App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            unoscore:
              'unoscore/**'

      - if: steps.changes.outputs.unoscore == 'true'
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./unoscore/public/ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
