name: Deploy Unoscore App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Filter
        uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            unoscore:
              './unoscore/**'

      - name: Install node 12.x
        if: steps.filter.outputs.unoscore == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build Unoscore App
        if: steps.filter.outputs.unoscore == 'true'
        run: cd ./unoscore && npm install && npm run build

      - name: Install surge on match
        if: steps.filter.outputs.unoscore == 'true'
        run: npm install -g surge

      - name: Run deployment on match
        if: steps.filter.outputs.unoscore == 'true'
        run: surge ./unoscore/public/ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
