name: Deploy Unoscore App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g surge
      - run: surge ./unoscore/public ${{ secrets.SURGE_DOMAIN }} ${{ secrets.SURGE_TOKEN }}
