name: Deploy Unoscore App

on: [push]

jobs:
  surge-deploy:
    name: Deploying to ${{ secrets.SURGE_DOMAIN }}
    runs-on: ubuntu-latest
    steps:
      - name: Install surge and run deployment
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./unoscore/public/ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
